#pragma once

/// @brief Événements personnalisés
/// @enum Events
enum Events {
	BACK_TO_MAINMENU_CLICK = 32768,
	BACK_BUTTON_CLICK,
	RESET_OPTIONS_BUTTON_CLICK,
	APPLY_CHANGES_BUTTON_CLICK,
	DEC_RESOLUTION_BUTTON_CLICK,
	INC_RESOLUTION_BUTTON_CLICK,
	DEC_LANGUAGE_BUTTON_CLICK,
	INC_LANGUAGE_BUTTON_CLICK,
	PLAY_BUTTON_CLICK,
	OPTIONS_BUTTON_CLICK,
	QUIT_BUTTON_CLICK,
};